import {server} from '../config'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { lessons } from '../mock_data/data'

import * as React from 'react';
import Chip from '@mui/material/Chip';
import { Button, Container, Grid, Paper, InputBase, IconButton } from '@mui/material'
import SearchIcon from '@mui/icons-material/Search';
import Typography from '@mui/material/Typography';
import Nav from '../components/Nav'
import LessonCard from '../components/LessonCard'


export default function Home() {
  return (
    <div>

      {/* Temporary Background */}
      <div className='elipse-8'>

      </div>
      <div className='elipse-10'>
        
        </div>
        <div className='elipse-11'>
        
        </div>
        <div className='elipse-6 '>
        
        </div>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />

      <Container sx={{ mb: 10 }}>
        <Grid container
          direction="column"
          justifyContent="flex-start"
          alignItems="center"
          sx={{ mt: 5 }}>

          <Grid item>
            <Typography variant="h1">
              Search Lesson        
            </Typography>
          </Grid>

          <Grid item sx={{ mt: 3 }}>
            <Paper elevation={0}
              component="form"
              sx={{ px: "4px", py: "2px", borderRadius: 10, display: 'flex', alignItems: 'center', width: '850px'}}>
              <IconButton sx={{ p: '20px' }} aria-label="search">
                <SearchIcon />
                {/* <PageviewIcon /> */}
                {/* <FindInPageIcon /> */}
              </IconButton>
              <InputBase
                sx={{ ml: 1, flex: 1 }}
                placeholder="What surah would you like to investigate?"
                inputProps={{ 'aria-label': 'What surah would you like to investigate?' }}
              />
              </Paper>
          </Grid>

          <Grid item sx={{ mt: 10 }}>
            <Chip color="secondary" label="Lessons" />
          </Grid>
        </Grid>

        <Grid container direction="row"
        justifyContent="flex-start"
        alignItems="flex-start" sx={{ mt: 4 }} >
          {lessons.map(lesson => 
            <LessonCard id={lesson.id} name={lesson.name} name_ar={lesson.name_ar} meaning={lesson.meaning} verses={lesson.verses}/>
          )}
        </Grid>
      </Container>

      
      <footer className={styles.footer}>
        <a> Quran Journey </a>
      </footer>
    </div>
  )
}

export const getStaticProps = async () => {
  const res = await fetch(`${server}/api/lessons`)
  const lessons = await res.json()

  return {
    props: {
      lessons,
    }
  }
}